name: Webhook: Play Spotify Playlist by UID
        description: >
          Trigger a Spotify playlist when a webhook is received with an RFID UID.
          Useful for M5NanoC6 RFID projects.
        domain: automation
        input:
          webhook_id:
            name: Webhook ID
            description: The webhook endpoint to listen to.
            selector:
              text:
          device_id:
            name: Media Player Device ID
            description: Device ID of the media player that should play the playlist.
            selector:
              device:
                integration: spotify
          playlist_map:
            name: Playlist UID Map
            description: >
              A mapping of RFID tag UIDs to Spotify playlist IDs. Use the format:
              "UID": "Spotify Playlist ID"
            default: {}
            selector:
              object:

trigger:
  - platform: webhook
    webhook_id: !input webhook_id
    allowed_methods:
      - POST
      - PUT
      - GET
    local_only: false

variables:
  uid: "{{ trigger.json.UID }}"
  playlist_map: !input playlist_map
  selected_playlist: "{{ playlist_map[uid] if uid in playlist_map else None }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ selected_playlist != None }}"
        sequence:
          - service: media_player.play_media
            target:
              device_id: !input device_id
            data:
              media_content_id: "https://open.spotify.com/playlist/{{ selected_playlist }}"
              media_content_type: playlist
    default:
      - service: telegram_bot.send_message
        data:
          message: "Tag was not found in playlist mapping: {{ trigger.json.UID }}"

mode: single
